### ISSUE TITLE
Skjemakatalogen - finne, forstå og få til?

### ISSUE THREAD

**Issue by OlaSvahnDigdir** [Altinn/altinn-infoportal-optimizely#222]
**Objektiv**
Målet med re-designen är att brukere skall:
- Finne riktig skjema/tjeneste
- Forstå hva de må gjøre for å kunne levere skjema eller utføra en tjeneste
- Ha godt nok kunskap før att fylle ut och levere skjema/slutføra tjeneste

**Inkluderar**
- Hvordan skall brukere finne ett skjema? (arkitektur)
- Hvilken informasjon skall brukere få om ett skjema?
- Når skall informasjonen presenteras?
- Hvordan skall informasjonen presenteras?

**---Todo---**

**Research**
- [ ] Dybdeinterjuer - hvordan vet brukere vilket skjema, når og hvordan de fyller ut det?
- [ ] Brukerstatistikk - siteimprove

**Effektmåling**

Fyll ut senere

**Designaktiviteter**
- [ ] Workshop: Hvilke sidetyper trenger vi når vi oppdaterer altinn.no i lys av moderniseringen av altinn? (5. september)
- [ ] Workshop: Hvilken innsikt trenger vi og hva har vi? Dvs innsikt vi trenger til oppdateringen. (23. september)

**Designoppgaver**

Fyll ut senere
